### ISSUE TITLE
为什么找不到hdzui的一些api

### ISSUE THREAD

**Issue by alexzshl** [hunzsig-warcraft3/h-lua-demo#5]
在一些早期的视频中看到了 hdzui.frameSetText, hdzui.frameSetSize 等api, 但是目前的api里面没有

**Comment by hunzsig** [comment]
请使用新版API：https://github.com/hunzsig-warcraft3/h-lua-sdk/blob/main/depend/h-lua/lib/japi.lua
DzFrameSetText、DzFrameSetSize

**Comment by xxqq9527** [comment]
QQ群325338043，群里又详细资料
